# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'loan-shop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJExtension'
pod 'UMengAnalytics'
  # Pods for loan-shop

end
